name: publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Ensure GitHub Release with extension TER artifact and publishing to TER
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            echo "ERR: Invalid publish version tag: ${{ github.ref }}"
            exit 1
          fi

      - name: Get version
        id: get-version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # Note that when release already exists for tag, only files will be uploaded and lets this acting as a
      # fallback to ensure that a real GitHub release is created for the tag along with extension artifacts.
      - name: Create release and upload artifacts in the same step
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          name: "[RELEASE] ${{ env.version }}"
          generate_release_notes: true
          files: |
            LICENSE
          fail_on_unmatched_files: true
